services:
    # Seralizer Adapter
    api_response.serializer_adapter:
        class: MattJanssen\ApiResponseBundle\Serializer\Adapter\SerializerAdapterInterface
        synthetic: true

    # Compiler
    api_response.compiler.api_config: # Generated in ApiResponseExtension compile pass.
        class: MattJanssen\ApiResponseBundle\Compiler\ApiConfigCompiler
        arguments:
            - %api_response.defaults%
            - %api_response.paths%

    # Subscriber
    api_response.subscriber.api_response:
        class: MattJanssen\ApiResponseBundle\Subscriber\ApiResponseSubscriber
        tags: [ { name: kernel.event_subscriber } ]
        arguments:
            - "@api_response.generator.api_response"
            - "@api_response.compiler.api_config"
            - "@logger"
            - %kernel.debug%
            - %api_response.log_trigger%

    # Factory
    api_response.factory.serializer_adapter:
        class: MattJanssen\ApiResponseBundle\Factory\SerializerAdapterFactory
        arguments:
            - "@service_container"

    # Generator
    api_response.generator.api_response:
        class: MattJanssen\ApiResponseBundle\Generator\ApiResponseGenerator
        arguments:
            - "@api_response.factory.serializer_adapter"
